### ISSUE TITLE
Throw IllegalArgument excepion for null as values on set

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-csharp#32]
A customer was trying to set `null` values and currently they get the following experience. Should we allow `null` as value? If we don't want to allow `null` values we should return `IllegalArgument` exception or something similar that is consistent between set methods. 

With string key
```console
Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at Google.Protobuf.ByteString.CopyFrom(String text, Encoding encoding)
   at Google.Protobuf.ByteString.CopyFromUtf8(String text)
   at MomentoSdk.ScsDataClient.Convert(String s)
   at MomentoSdk.ScsDataClient.Set(String cacheName, String key, String value, UInt32 ttlSeconds)
   at MomentoSdk.Responses.SimpleCacheClient.Set(String cacheName, String key, String value, UInt32 ttlSeconds)
   at MomentoApplication.Program.Main(String[] args) in /Users/eaw/dev/momento/client-sdk-examples/dotnet/MomentoExamples/MomentoApplication/Program.cs:line 25
```

With byte key
```console
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.Protobuf.ByteString.CopyFrom(Byte[] bytes)
   at MomentoSdk.ScsDataClient.Convert(Byte[] bytes)
   at MomentoSdk.ScsDataClient.Set(String cacheName, Byte[] key, Byte[] value, UInt32 ttlSeconds)
   at MomentoSdk.Responses.SimpleCacheClient.Set(String cacheName, Byte[] key, Byte[] value, UInt32 ttlSeconds)
   at MomentoApplication.Program.Main(String[] args) in /Users/eaw/dev/momento/client-sdk-examples/dotnet/MomentoExamples/MomentoApplication/Program.cs:line 25
```

**Comment by malandis** [comment]
I've added null argument checks everywhere. We will refactor the exception type shortly.
